change = float(input())
num_coins = 0

while change != 0:
    if change >= 2:
        change = round(change - 2, 2)
        num_coins += 1
    elif change >= 1:
        change = round(change - 1, 2)
        num_coins += 1
    elif change >= 0.5:
        change = round(change - 0.5, 2)
        num_coins += 1
    elif change >= 0.2:
        change = round(change - 0.2, 2)
        num_coins += 1
    elif change >= 0.1:
        change = round(change - 0.1, 2)
        num_coins += 1
    elif change >= 0.05:
        change = round(change - 0.05, 2)
        num_coins += 1
    elif change >= 0.02:
        change = round(change - 0.02, 2)
        num_coins += 1
    elif change >= 0.01:
        change = round(change - 0.01, 2)
        num_coins += 1
print(num_coins)